apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
namePrefix: staging-

resources:
- ../../base

components:
  - ../../variants/prod

patchesStrategicMerge:
- staging-settings.yml
- version.yml
- replicas.yml