---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  annotations:
    codefresh.io/app: simple-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: GPU_ENABLED
          value: "1"
        - name: CACHE_SIZE
          value: "1024kb"
        - name: PAGE_LIMIT
          value: "25"
        - name: SORTING
          value: "ascending"    
        - name: N_BUCKETS
          value: "42" 
        imagePullPolicy: Always
        image: docker.io/javadza/environment-promotion_03:1.0
        ports:
        - containerPort: 8080