name: dev-staging-version-promotion

on:
  push:
    branches: [ "master" ]
    paths:
      - 'envs/dev/version.yml'

jobs:

  promote-version:
    runs-on: ubuntu-latest
    name: Promote version from dev to staging

    steps:
    
        - name: Checkout Deployment repository
          uses: actions/checkout@v3
          with:
            repository: JavadZahrabi/deploymentt
            path: ./deploymentt

        - name: copy version.yml
          run: |
              cp -R ./deploymentt/envs/dev/version.yml ./deploymentt/envs/staging
        
        - name: Push version to staging
          run: |
            cd ./deploymentt
            git add .
            git config user.name JavadZahrabi
            git config user.email ja.zahrabi@gmail.com
            git commit -am "version.yml promoted to staging"
            git push