name: staging-prod-version-promotion
on:
  workflow_run:
    workflows: [ "dev-staging-version-promotion" ]
    types:
      - completed

jobs:

  promote-version:
    runs-on: ubuntu-latest
    name: Promote version from dev to staging

    steps:
    
        - name: Checkout Deployment repository
          uses: actions/checkout@v3
          with:
            repository: JavadZahrabi/deploymentt
            path: ./deploymentt

        - name: copy version.yml
          run: |
              cp -R ./deploymentt/envs/staging/version.yml ./deploymentt/envs/prod
        
        - name: Push version to prod
          run: |
            cd ./deploymentt
            git checkout -b "prod"
            git add .
            git config user.name JavadZahrabi
            git config user.email ja.zahrabi@gmail.com
            git commit -am "version.yml promoted from staging to prod"
            git push --set-upstream -f origin prod
  
  Prod-Auto-PR:
    needs: promote-version
    runs-on: ubuntu-latest

    steps:

        - name: checkout
          uses: actions/checkout@v3

        - uses: repo-sync/pull-request@v2
          name: pull-request
          with:
            source_branch: "prod"
            destination_branch: "master"
            pr_title: "promote staging version to prod"
            pr_body: "An automated PR from prod"
            pr_reviewer: "JavadZahrabi"
            pr_draft: true
            github_token: ${{ secrets.ACTIONS_TOKEN }}
